### ISSUE TITLE
Handling two connections in one delta 

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#127]
When some sites get bigger, it contains multiple servers at distributed locations. One of the scenario is that we want to create a connection between two servers of same site. For example, from DTN at Guam to DTN at Hawaii, which are under control of same site RM. 

In this case, a delta will consists of two connections as one DTN will connect to a WAN switch and come back to the other. 

Other scenarios include create parallel connections in one request. 

Assigned to @juztas

**Comment by juztas** [comment]
@xi-yang can you prepare template on dev instance for this?

**Comment by juztas** [comment]
Solved here: https://github.com/sdn-sense/siterm/pull/157

SiteRM loops over all connections - so it can be 1 to N

**Comment by juztas** [comment]
Additional fix: https://github.com/sdn-sense/siterm/pull/161
