### ISSUE TITLE
Problem with simultaneous requests

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#128]
When DMM issued two connection requests for ultralight --to-- ultralight1 and ultralight --to- UCSD at the same time, ultralight RM would fail to configure (completely) switch for one of the two. 

We tried this twice, first time one of the two connections was stuck in COMMITTED. The second time both were stuck in COMMITTED. 

We went back to do one connection only. Then it always worked. 

Assign to @juztas to fix.

**Comment by xi-yang** [comment]
In another test, I created 5x L2 connections UCSD -- Caltech. They were not exactly simultaneous, but with around 1 minute in between. 4x connections went Create - READY. 1x got stuck in Create - COMMITTED. 

Just like the above (other) scenario, L2 part had trouble. So we can use this as a test scenario for the debugging.

**Comment by juztas** [comment]
Do you have py template for this? As we have library - we should think of an easier way to submit (that would help me to test out such options for future)

**Comment by juztas** [comment]
Solved here: https://github.com/sdn-sense/siterm/pull/157

**Comment by juztas** [comment]
Can you please save the full delta which was submitted? And also template
for debugging. Thanks
