### ISSUE TITLE
Normalize the mrs:capacity unit

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#130]
I see very different capacity numbers that suggest they are implying different unit. I assume the default will be bps. 

```
<urn:ogf:network:maxgigapop.net:2013:s0:1_1> a nml:BidirectionalPort ;
    mrs:capacity 40000 ;
    nml:hasLabelGroup <urn:ogf:network:maxgigapop.net:2013:s0:1_1:vlan-range> ;
    nml:isAlias <urn:ogf:network:es.net:2013::wash-cr6:1_1_c6_1:+> .

<urn:ogf:network:maxgigapop.net:2013:s0:1_2> a nml:BidirectionalPort ;
    mrs:capacity 100000000000000 ;
    nml:hasLabelGroup <urn:ogf:network:maxgigapop.net:2013:s0:1_2:vlan-range> .
```

**Comment by xi-yang** [comment]
According to the MRML definition, the value of mrs:capacity should be a string. 
```
    <owl:DatatypeProperty rdf:about="http://schemas.ogf.org/mrs/2013/12/topology#capacity">
        <rdfs:domain rdf:resource="http://schemas.ogf.org/nml/2013/03/base#NetworkObject"/>
        <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    </owl:DatatypeProperty>
```

So we could add unit in there.

For example, `mrs:capacity "40000mbps"` or simply `"40000000000"`.

**Comment by juztas** [comment]
Wan link speeds were modified for all RM configs: https://github.com/sdn-sense/rm-configs/commit/543840d8f68e74b15544977f90e863a4f8fe945b
This does affect only overrides (switches already report in mbps)
