### ISSUE TITLE
Change of ipv6-subnet-pool NetworkAddress

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#196]
The change from `ipv6-subnet-pool` into `ipv6-subnet-pool-list` breaks model SPARQL query and cause compile failures. 

Also the value strings in the pool look weird. 

<img width="483" alt="Screen Shot 2022-09-09 at 9 07 47 PM" src="https://user-images.githubusercontent.com/6596456/189462905-331c7174-7a79-4198-92a4-1e9eb5a79232.png">

**Comment by juztas** [comment]
Solved here: https://github.com/sdn-sense/siterm/pull/197

UCSD and Caltech redeployed (only those two sites use dev release)
