### ISSUE TITLE
L3 model issues 

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#198]
Looks like we are missing ports under routingService. 

<img width="970" alt="Screen Shot 2022-09-10 at 10 27 10 PM" src="https://user-images.githubusercontent.com/6596456/189538158-f36eddd4-2b50-4fec-9fd0-eef267d048ab.png">

Let's keep the issue open until all modeling issues are fixed the the RUCIO service profile can compile correctly.

**Comment by juztas** [comment]
RST ports added. fix here: https://github.com/sdn-sense/siterm/pull/199

**Comment by xi-yang** [comment]
Model looks good now. I was able to bring the service instance up and cancel. and then reintate and cancel. (New OpenNSA driver is in place and ONSA seems more stable.)

**Comment by juztas** [comment]
@xi-yang Can you issue it once again and leave it active?

**Comment by juztas** [comment]
Agent Ruler alerted in grafana during provisioning. Error related due to missing formatting in the commands. Fix: https://github.com/sdn-sense/siterm/pull/200

**Comment by juztas** [comment]
Closing. All solved. Release new version
