### ISSUE TITLE
PortChannel issue (lldp and mapping ports/portchannels)

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#209]
In case we have PortChannel, e.g.
Dell Z9100 lldp reports:
 Hu 1/8         lrt-sdn-r02-ari...Ethernet15/1                       44:4c:a8:55:2c:dd
 Hu 1/9         lrt-sdn-r02-ari...Ethernet16/1                       44:4c:a8:55:2c:dd
Arista lldp reports:
Et15/1     4c76.25e8.44c0                   hundredGigE 1/8            120
Et16/1     4c76.25e8.44c0                   hundredGigE 1/9            120

But in modeling we have:
![image](https://user-images.githubusercontent.com/646582/190679285-2ae6396a-2e4f-4a89-a3ac-42d38feb0703.png)
![image](https://user-images.githubusercontent.com/646582/190680190-ff7cc7e8-28b0-401e-868a-a74ef3587009.png)
![image](https://user-images.githubusercontent.com/646582/190680410-71260462-2e5e-4a50-82b6-7ed27b6457b1.png)

So in case we have this situation:
Z9100 Port 1/8 connected to Arista Eth15/1 (and back)
Z9100 Port 1/9 connected to Arista Eth16/1 (and back)
Z9100 (1/8 and 1/9) are under PortChannel 103
Arista  (Eth15/1 and 16/1) are under PortChannel111

On Modelling we have connection (isAlias) between Port's itself and also we have hasBidirectionalPort under PortChannels. It might break path computation... @xi-yang comments?

**Comment by xi-yang** [comment]
If portChannel is what we we going to control on, then we can leave out the children ports. 

Rule of thumb is "model what you want to control".

**Comment by juztas** [comment]
And should we exclude mapping between Ports itself? Would it break if it remains?

**Comment by juztas** [comment]
If we keep it what will happen, it will have isAlias between:
Z9100 Port 1/8 and Arista Eth15/1
Z9100 Port 1/9 and to Arista Eth16/1
PortChannel 103 (z9100) and PortChannel111 (Arista)

Question really is - what orchestrator will use for path between 2 hosts:
host1 eth0 <-> hundredGig 1/7 Z9100 <-> (WHAT IT WILL USE HERE Port itself, or PortChannel?) <-> Arista Eth1 <-> Host2 eth0

**Comment by xi-yang** [comment]
You can still keep port under portChannel but without isAlias at port level if you do not intend to pass traffic on them separately.

**Comment by juztas** [comment]
There is nothing to do on this ticket. Leaving it for SiteAdmins to decide what can/wish to be exposed. It can be easily controlled via config file
