### ISSUE TITLE
Add nml:name to Node and Interface of hosts and switches

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#252]
The monitoring systems need to correlate the names from SENSE model with the data collecting targets.

In this example the host / switch name can be a FQDN or some name the RM makes up. The interface /port name must be the ifName we see in SNMP.  
  https://github.com/esnet/sense-rtmon/blob/main/config_flow/updated_config.yml

If there are multiple `nml:name`, we can add a NetworkAddress with type `sense-rtmon:name`.

**Comment by juztas** [comment]
Solved here: https://github.com/sdn-sense/siterm/pull/254
