### ISSUE TITLE
Allow to filter out specific Port for RealTimeMon

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#282]
SiteRM need new API Param for debug calls to filter out specific interface.

**Comment by juztas** [comment]
@xi-yang FYI

**Comment by xi-yang** [comment]
Let's start with an experiment. Adding 
```
"flow_id": "36205159-522f-4c6c-831d-2953354b6b57",
"flow_spec": [
   {
   "node": "T2_US_Caltech_Test:dellos9_s0",
   "port":   "hundredGigE_1-10",
   "vlan":  "3113"
   },
   {
   "node": "T2_US_Caltech_Test:dellos9_s0",
   "port":   "Port-Channel501",
   "vlan":  "3113"
   },
   {
   "node": "T2_US_Caltech_Test:sandie-1.ultralight.org",
   "port":   "mlx4p2s1",
   "vlan":  "3113"
   }  
]
```

See what we can tailor into for the export. Ideally, we want
1. Only data related to the `flow_spec` is exported (in reality, we may have allow more. For example, everything from the nodeExporter.) 
2. Each tailored data row  carries the exact `flow_id`. 

If we can do this, then we can extend into a more scalable solution.

**Comment by juztas** [comment]
https://github.com/sdn-sense/siterm/pull/290
