### ISSUE TITLE
Common handling of service schedule lifetime model

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#293]
This is to normalize the modeling and handling of scheduled L2 and L3 resources as applicable to Site-RM. 

The feature requirements described in https://github.com/esnet/SENSE-Testbed/issues/92#issue-820370980 and https://github.com/esnet/SENSE-Testbed/issues/92#issuecomment-789205102.

This will be similar to Items 1, 2 and 4 for the SENSE-O NSIDriver feature https://github.com/esnet/StackV/issues/1150.

Note: A new version of SENSE-O now will model VLAN Port using instance specific URIs. Instead of having multiple lifetime and bandwidthSerivce under the same vlan-port resource, there will be separate model branch each vlan-port. Make sure the RM code can handle that and also regenerate the URIs correctly.

**Comment by xi-yang** [comment]
Some modeling examples with lifetime and networkStatus. 
https://github.com/esnet/sense-rm/issues/14#issuecomment-1636295188

**Comment by juztas** [comment]
That should be already in place for L2 and BW (or we will have to see once new deltas arrive). Testing can be done together with networkStatus (fix discussed here: https://github.com/sdn-sense/siterm/issues/294). 

Current scheduling - does not support scheduling for L3 Requests (as the example does not have it and there was no use case for that yet). Once an example is available - we could also support Scheduling for L3.

Closing this and for bugs - feel free to open new issue with details
