### ISSUE TITLE
Host IP address URI and modify problems

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#319]
1. URI problem: https://github.com/esnet/StackV/issues/1183#issuecomment-1747315214
2. Modify problem: https://github.com/esnet/StackV/issues/1183#issuecomment-1747325745

**Comment by xi-yang** [comment]
> Modify - that is a feature. (We never used that)

When we have old IP in reduction and new IP in addition, we need to delete the old IP. Right now we will end up with both IPs. This is a bug instead of feature.

**Comment by juztas** [comment]
@xi-yang, Could you submit this to UMD and leave it in a broken state with 2 IPs?

**Comment by xi-yang** [comment]
> @xi-yang, Could you submit this to UMD and leave it in a broken state with 2 IPs?

@juztas VLAN 3607. You can see two IPs there 10.251.88.19 and .20/24.

**Comment by xi-yang** [comment]
For IPv6 address on BGP peer tunnel, the URI SENSE-O pushed is like
```
urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3610:ipv6-address+fc00_3600_0_0_0_0_1_1050_64
```

Then the pulled model has:
```
urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3610:ipv6-address+None
```

**Comment by juztas** [comment]
We should make things equal. e.g., from the previous message:
```
In SENSE-O delta, an host IPv4 address has URI urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3603:ipv4-address+10.251.89.14 while the RM models it as urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3603:ipv4-address+10.251.89.14_24.
```
So delta for ipv4 had:
```
urn:ogf:network:maxgigapop.net:2013:ptxn-sense-v1.maxgigapop.net:enp1s0:vlanport+3603:ipv4-address+10.251.89.14
```
but for ipv6:
```
urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3610:ipv6-address+fc00_3600_0_0_0_0_1_1050_64
```
Why one has netmask in it, and another does not? Can we have them equal come from orchestrator?

**Comment by xi-yang** [comment]
@juztas Let's not rely on sense-o-dev to test the modify. I am using development code on my localhost for this. 

For IPv4, I have changed the URI from the orchestrator to match your style, i.e., ending with prefix length like `_24`. So that is good. 

For IPv6, you will need to fix your modeling, i.e., the `_None`. 

In the long run, we generally should ask the RMs to strictly reproduce the URIs originated from the orchestrator.

**Comment by juztas** [comment]
Modify and URI changes should be in place here: https://github.com/sdn-sense/siterm/pull/322
Once action validates pull request - will create new tags and update Arista, Caltech, UCSD.
For IP removal - it will check what IPs are in ALL active deltas, and remove any IP from SENSE controlled vlans if it is in address-pool. If IP is not in address-pool (e.g. set manually) - it will leave it and raise warning in logs.

**Comment by xi-yang** [comment]
The IPv6 address on BGP tunnel still does not look right. 

The SENSE-O pushed:
`<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3610:ipv6-address+fc00_1794_0_0_0_0_1_d04_64>`

The Site-RM made:
`<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3610:ipv6-address+fc00__1794____1__d04>`


Again, try making the URI format-agnostic and record and replay any URI string a whole.

**Comment by juztas** [comment]
Change done. Caltech/SDSC/LA redeployed with a new change, and the URI is as expected.
```
<urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3619:ipv6-address+fc00_1781_0_0_0_0_0_368c_64> a mrs:NetworkAddress ;
    mrs:type "ipv6-address",
        "unverifiable" ;
    mrs:value "fc00:1781::368c/64" .
```

**Comment by xi-yang** [comment]
Was that actually deployed? I still see this.
```
Yours:
urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3610:ipv6-address+fc00_1794_0_0_0_0_0001_0d05_64

vs

Mine:
urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3610:ipv6-address+fc00_1794_0_0_0_0_1_d05_64
```

It will probably be hard to construct a format perfectly matching the format from Java IPAddress.toNormalizedString(), as one missing 0 will make the difference. Some db cached metadata from deltas may be required to regenerate this.

**Comment by juztas** [comment]
SiteRM builds a model based on the current state of the infrastructure. Caching is not an option - some things come not from the delta but from the devices themselves (so I would need to make that same format). So, these IPs are all valid:
```
fc00:1794:0:0:0:0:1:d05/64
fc00:1794::1:d05/64
fc00:1794:0000:0000:0000:0000:0001:d05/64
```
Python and Java do it differently, and seems a good way would always be to use a fully exploded IP, e.g., `fc00:1794:0000:0000:0000:0000:0001:d05/64`. It is possible also to make a custom parser and export it in Java's preferred way - but I think fully exploded IP is a better approach.

**Comment by xi-yang** [comment]
> SiteRM builds a model based on the current state of the infrastructure. Caching is not an option - some things come not from the delta but from the devices themselves (so I would need to make that same format). So, these IPs are all valid:
> 
> ```
> fc00:1794:0:0:0:0:1:d05/64
> fc00:1794::1:d05/64
> fc00:1794:0000:0000:0000:0000:0001:d05/64
> ```
> 
> Python and Java do it differently, and seems a good way would always be to use a fully exploded IP, e.g., `fc00:1794:0000:0000:0000:0000:0001:d05/64`. It is possible also to make a custom parser and export it in Java's preferred way - but I think fully exploded IP is a better approach.

We should not working on the format of URI at all. Let's stick to the rule of thumb: Resource URI is an imnutable string identifier and the origin of the URI must be respected. 

We could hack to make the format match but this approach will have many pitfalls for future problems.

In embedded SENSE RM / Driver codes, we used a metadata structure to cache / index the URIs learned from deltas. It is just about mapping the identifiers, not about any ground truth from the infrastructure states.

**Comment by juztas** [comment]
Change done to represent in an expected format. 
```
<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3610:ipv6-address+fc00_1794_0_0_0_0_1_d04_64>
```
We should talk about the current issues of modeling and URI in the near future.

**Comment by xi-yang** [comment]
That looks good. If I push an extra statement like 
```
<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3604:ipv6-address+fc00_3615_0_0_0_0_1_9c2_64>
        <http://schemas.ogf.org/mrs/2013/12/topology#value>
                "fc00:3615:0:0:0:0:1:9c2/64" .
```

But you already had: 
```
<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3604:ipv6-address+fc00_3615_0_0_0_0_1_9c2_64>
        <http://schemas.ogf.org/mrs/2013/12/topology#value>
                "fc00:3615::1:9c2/64"
```

Those are identical IP but not identical strings. Would you jus ignore that?

**Comment by juztas** [comment]
SiteRM checks all values and checks if that is the same (and it is), So it will be ignored (no changes will be done/executed).

For consistency, changes were done to have it Java expected way:
```
<urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103:vlanport+3610:ipv6-address+fc00_1794_0_0_0_0_1_d04_64> a mrs:NetworkAddress ;
    mrs:type "ipv6-address",
        "unverifiable" ;
    mrs:value "fc00:1794:0:0:0:0:1:d04/64" .
```

**Comment by juztas** [comment]
Changes done and all is fixed. Please, reopen if needed.
