### ISSUE TITLE
Change of VLAN Port URN to service specific

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#354]
This is related to #294. To support multiple schedules / lifetimes  on a same VLAN port (and derived bandwidthService), we need to change the vlan port URN (and bwService URN) from the current fixed format like `urn:ogf:network:nrp-nautilus.io:2020:sn3700_s0:PortChannel501:vlanport+3986` into something that differs by service instance (with UUID embedded in the URI). 

This way we can differentiate the schedule / bandwidth service by different service instances. Currently all RMs support this but his would fail to verify with Site-RM which might be making assumption of the URI format.

SENSE-O is holding back a change because of the Site-RM compatibility on this. If this is fixed, we can apply the SENSE-O change as well.

**Comment by juztas** [comment]
First change to record URI in active state: https://github.com/sdn-sense/siterm/pull/407

**Comment by juztas** [comment]
First test done. Small fixes added here to keep track vlanuris and IP uris: https://github.com/sdn-sense/siterm/pull/452

**Comment by juztas** [comment]
Closing. Lets reopen new issue if there is an issue. We run this for quite some time
