### ISSUE TITLE
Address URN inconsistency 

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#362]
We pushed back the request that the RM should keep IPv6 address URN consistent as seen from SENSE-O deltas. 

Just want to have this on the TODO list to fix, along with the issue #354. 

When we started using the address pool service for ip allocation, this becomes more important as we are affiliate an IP allocation to this URN. The SENSE-O is relying on the correct URN to verify if the allocation can be removed and recycled. So with inconsistent URN, we run the risk of duplicate allocations. 

Example inconsistency:

SENSE-O delta: `urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-13:vlanport+3985:ipv6-address+fc00_3986__2_64`

Site-RM model: `urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-13:vlanport+3985:ipv6-address+fc00_3986_0_0_0_0_0_2_64`

**Comment by xi-yang** [comment]
I modified SENSE-O model to generate normalized IP address string. This should help for now.

Let's keep this issue open until we can work with any string values (format agnostic).

**Comment by juztas** [comment]
Same should be handled here where it keeps track of submitted delta URIs for IPs and use those if present. First test done. Small fixes added here to keep track vlanuris and IP uris: https://github.com/sdn-sense/siterm/pull/452 

Still need more testing.

**Comment by juztas** [comment]
There is an issue with Unique IP URIs - it keeps adding an additional to the key - need to look into it.

**Comment by juztas** [comment]
Already in place for quite some time. No new issues.
