### ISSUE TITLE
Reduction failed to delete one of the VLAN ports with dual connections in a delta

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#369]
A dual connection delta was provisioned successfully on LA-Arista as part of the connection below.

<img width="1026" alt="Screen Shot 2023-11-10 at 1 42 40 PM" src="https://github.com/sdn-sense/siterm/assets/6596456/89a8a9a4-2b45-43e9-bbac-ca5f1c73a850">

Upon cancel, however, one out of the four VLAN ports did not go away. 

<img width="955" alt="Screen Shot 2023-11-10 at 9 28 25 PM" src="https://github.com/sdn-sense/siterm/assets/6596456/02c56378-11b3-4dee-8d73-5beb88326886">

**Comment by juztas** [comment]
Solved and tested during SC: https://github.com/sdn-sense/siterm/pull/373/files
