### ISSUE TITLE
readonly database error in FE container

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#37]
@juztas 
The default permission for all config files is 644. Looks like sqlite.db needs 666. After I change it to the below, it worked. 

Alternatively we can change the owner from `apache` to the actual db process user. 

```
[root@sitefe-5f4576b94-86l2c /]# ls -l /opt/config/T2_US_UMD/sqlite.db 
-rw-rw-rw-. 1 apache apache 314368 Jul 21 13:53 /opt/config/T2_US_UMD/sqlite.db
```

**Comment by xi-yang** [comment]
With more tests, the `readonly` problem popped up again, although not always.

**Comment by juztas** [comment]
Fixes: https://github.com/sdn-sense/siterm/pull/39
