### ISSUE TITLE
Support multiple connection IDs in a single delta request

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#41]
It gave 500 error. See the below FE logging. @juztas 

![Screen Shot 2020-09-10 at 12 17 05 PM](https://user-images.githubusercontent.com/6596456/93098259-a8643480-f674-11ea-8a11-d31fbf01ac7a.png)

**Comment by juztas** [comment]
Which FE? Need full delta

**Comment by juztas** [comment]
It received multiple deltas in one and this is not supported by FE.

**Comment by xi-yang** [comment]
On Caltech. It is one delta with multiple connections (SwitchingSubnet and VLANs).

**Comment by juztas** [comment]
That is not supported

**Comment by xi-yang** [comment]
Can we support that? Having multiple connections in one service is a basic requirement from orchestration perspective.

**Comment by juztas** [comment]
I vaguely remember having this discussion and you told this is not mandatory.

**Comment by xi-yang** [comment]
That was temporary plan. You could always use multiple services instead of multiple connections in one service. 

However, we are starting giving AutoGOLE people SENSE-O account on the testbed. For now, we give them intents we composed. In a few months, we will let some compose their own intents. They may composed ones that have multiple connections. So we need to test all the possible cases and make sure they work. 

Would support for multiple connections in one delta involve big changes?

**Comment by juztas** [comment]
That should not be a big change. Can you post full delta with multiple connections and I will take a look

**Comment by xi-yang** [comment]
@juztas Looks like you were using SENSE-O for tests. Do you still need the delta posted here?

**Comment by juztas** [comment]
no, i use sense-o

**Comment by juztas** [comment]
Pull request here: https://github.com/sdn-sense/siterm/pull/43

Issues remaining: Consistency check with frontend, some cases are:
start/end time delta would be cancelled at FE, but this needs to be propagated to FE. This check was disabled right now.

**Comment by juztas** [comment]
For reference: https://github.com/sdn-sense/siterm/issues/46

**Comment by juztas** [comment]
It supports multiple connections. There are a few remaining issues - will be solved in other tickets.
