### ISSUE TITLE
dup vlanport advertisement in DTN host model

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#42]
@juztas 

DTN-RM advertise the same vlanport twice under host interface. This was not an issue until we worked with the complex logic of Modify, which requires to one-to-one mapping between the pushed in the delta and in the pulled model.

As an example, under eth1 on MAX 180-134 host, we have both 
```
<urn:ogf:network:maxgigapop.net:2013:s0:13:180-134.research.maxgigapop.net:vlan:vlanport+3610>
and
<urn:ogf:network:maxgigapop.net:2013:s0:13:180-134.research.maxgigapop.net:eth1:vlanport+3610>
```

Only the latter was what we pushed with delta. We should not add the former. This dup modeling will break Modify logic.

<img width="939" alt="Screen Shot 2020-09-16 at 5 06 26 PM" src="https://user-images.githubusercontent.com/6596456/93392944-a13d5200-f83f-11ea-8c04-e40cac56c410.png">
<img width="868" alt="Screen Shot 2020-09-16 at 5 05 43 PM" src="https://user-images.githubusercontent.com/6596456/93392947-a13d5200-f83f-11ea-8f9a-942106b3c83e.png">

**Comment by juztas** [comment]
That should not happen... Can I get access to 206.196.180.134? 

I tried my UMD logins, I can't access it. Thought I can access 131 (master)

**Comment by xi-yang** [comment]
@juztas The old kerberos server at MAX no longer works. I added you following ssh key to user `centos` for both hosts.
Try : ssh centos@206.196.180.131/134
```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAz8+n6WAfUVfEGe0QoJnJPTb3Yo3N5slmw4PoWLBKQJlmgxlpCVG8xrCEbSUljZuYmvd+2zW+RjawAqwBmBqkE/Mcd0jK5w0VqLR0G0ncDKk7sgFgG03pCYgtirKAsjLiVExApb+vN9AjYARvAB7Q1cBupBBD+W8bMo8YARdBAP+vcwTwfdbWw4aAb8h1Dyd027vqWu2ndRcyX1cOC7/p8ABvobekM61uL0Y5VmXLmzfttRebplgkq4NCzTav7Emb15wm2dBcsyW4Fr6yRS6nCt+1vQNeNX263fERcXFSCFpNSEcY4EvvgF+kDIMgzO4timTrjcl+KrX+Ma+23/IZZQ== juztas@gmail.com
```

**Comment by juztas** [comment]
The Issue was introduced with this pull request: https://github.com/sdn-sense/siterm/commit/51000f22942e380178f3ff4e956aa13ccd05ee1b
 and it was when we had an issue with CERN DTN too long interface name and kernel limitations. So what happens is:
It reports it has eth1 for control. Whenever delta is received, delta has eth1 in name, but the real interface on the system will be named vlan.XXXX. How I can express in MRML that vlan.3610 of parent eth1?

**Comment by xi-yang** [comment]
We should always use whatever is in the delta. You can compose a different URI only if it is not provided by the delta.

**Comment by juztas** [comment]
But these are different:
```
<urn:ogf:network:maxgigapop.net:2013:s0:13:180-134.research.maxgigapop.net:vlan:vlanport+3610>
<urn:ogf:network:maxgigapop.net:2013:s0:13:180-134.research.maxgigapop.net:eth1:vlanport+3610>
```
Do you want me to revert VLAN.XXXX naming? That will break some DTNs with long interface names.

**Comment by xi-yang** [comment]
The URI can have `ifname:vlanport+xxxx` but you can still do `vlan.xxxx` naming. The idea is "do not parse and make sense of the URI string".

**Comment by juztas** [comment]
Take a look at UMD Model now and let me know

**Comment by xi-yang** [comment]
Looking good now. Will close the issue after a few more tests.
