### ISSUE TITLE
Host vlan interface IP NetworkAddress missing in model

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#479]
When a networkAddress (say of `ipv4-address` type) is pushed in delta, it got provisioned on the host along with the vlan sub interface. For example, as shown in the below. However, the `mrs:hasNetworkAddress` statement is absent from the advertised model. As this is a non-essential statement, it was not caught in verify process.

<img width="545" alt="Screenshot 2024-04-19 at 10 41 34 AM" src="https://github.com/sdn-sense/siterm/assets/6596456/8dd44262-3a0e-4144-b2d3-4d8932e99f44">

**Comment by juztas** [comment]
Fixed here: https://github.com/sdn-sense/siterm/pull/480
Ip address validation and recording unique uris was considering only dictionary. For host IPs - it is a str - so it is skipped and removed from model. Re-added check back.
