### ISSUE TITLE
Model pull returns wrong format from Caltech DTN-RM

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#50]
There might be some change on Caltech DTN-RM in past week. It now return the following JSON format
```
[
  [
    {
      "model": " ... ",
      "href": "https://sdn-dtn-1-7.ultralight.org:8443/T2_US_Caltech/sitefe/v1/models/711e0b7a-0193-11eb-9050-0242ac120002",
      "creationTime": "2020-09-28T14:03:53.000000Z",
      "id": "711e0b7a-0193-11eb-9050-0242ac120002"
    }
  ]
]
```

There is one more level of `[]` as compared to other DTN-RMs. For example on UMD RM, we see
```
[
  {
    "model":  " ... ",
    "href": "https://180-131.research.maxgigapop.net:8443/T2_US_UMD/sitefe/v1/models/383de642-0191-11eb-bdb2-a29872714432",
    "creationTime": "2020-09-28T13:48:02.000000Z",
    "id": "383de642-0191-11eb-bdb2-a29872714432"
  }
]
```

Also, Caltech DTN-RM agent container was crashed. I left it as is for investigation. @juztas

**Comment by juztas** [comment]
Fixed here.  https://github.com/sdn-sense/siterm/compare/smallfixes?expand=1
Agent down for an upgrade and testing

**Comment by xi-yang** [comment]
Fix verified

**Comment by juztas** [comment]
Agent reinstalled/restarted. Need to test extensively - if all ok - we change all other DTNs.
