### ISSUE TITLE
Instruct orchestrator that one of the services is down

### ISSUE THREAD

**Issue by juztas** [sdn-sense/siterm#66]
we should be able somehow instruct Orchestrator that one of the services is down and resource allocation/delta accept/model update might not work. 

For such cases Orchestrator should not send new delta request or model updates.

**Comment by juztas** [comment]
@xi-yang what is the best way to do that? It might not work via model update (if model update service is down it will not update it)

**Comment by xi-yang** [comment]
Right now, success with model pull is the only way we can tell when the RM has problem. That means if model update or agent has problem, we cannot catch it. 

We could ask the RM force a model pull failure in such cases. Or we have to rely on notification from external monitoring.

**Comment by juztas** [comment]
I think we should have:
1. not allow pull model if any FE service is down;
2. report other services status inside the model. if status is unknown or failed - orcestrator could mark that RM bad.

**Comment by juztas** [comment]
Do we need to instruct orchestrator on this? Not sure how it would use this information.

We have all logged, recorded and alarmed inside the prometheus/grafana - and alter to slack. We can easily extend this to include some mailing lists.

**Comment by juztas** [comment]
Closing. We have alarms. In case one service is down - it will alert to slack and we need to know the reason for service down
