### ISSUE TITLE
The RM mishandles a delta with both addition and reduction of connections

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#69]
In a service modify scenario, a delta may consists of a reduction of one VLAN connection and an addition of another VLAN. A VLAN connection model has all the regular statements of SwitchingSubnet, BidirectinalPort and Label etc. 

The RM accepted and committed such a delta normally. However, neither the resulted system change and modeling  was correct. Here are the observations.

- The new VLAN was added for the addition connection but the old VLAN for reduction remained in the system.
- Neither the addition nor reduction SwitchingSubnet is modeled. 
- Both VLANs showed as Bidirectional Ports under the DTN node (for example 180-134.research.maxgigaop.net) in the model. But neither showed under the interface (for example, 180-134.research.maxgigaop.net:eth1).

 @juztas I can provide you the delta reduction and addition models via email if needed.

**Comment by juztas** [comment]
Yes please send it via email

**Comment by juztas** [comment]
This needs to be verified with a new release (210208). It included few fixes to support this.

**Comment by xi-yang** [comment]
I am still seeing problems in my tests with Caltech Test1 RM. 

* In many cases, Modify got into READY meaning both reduction and reduction models were verified. But almost immediately after that, new model pull will tell the "addition" is gone in the model. It appeared that the addition of VLAN was performed and then quickly undone. 

* In one case, the reduction was also done but addition was never verified. This may be by the same cause as the above. The odd was just timing of model pull. 

The addition statements were not completely missing. One showed up there. 

![Screen Shot 2021-02-22 at 12 19 58 PM](https://user-images.githubusercontent.com/6596456/108750880-8f0ec080-750f-11eb-87fc-884009f0c73b.png)
![Screen Shot 2021-02-22 at 12 20 03 PM](https://user-images.githubusercontent.com/6596456/108750882-8f0ec080-750f-11eb-835a-b1214175ebbd.png)

**Comment by juztas** [comment]
I need delta UIDs for those

**Comment by xi-yang** [comment]
> I need delta UIDs for those

The modify delta ID = 03c570cb-694a-4246-a074-2309430e1385.
The original delta ID = 4dacb5f9-d3b6-4e96-b6a0-1c3cac7083a5.

ServiceInstanceUUID = 503799b7-9f8e-4598-bb1f-2f7093ac638e.

**Comment by juztas** [comment]
I see like 10 tries to do the same thing ;)) That complicates debugging

**Comment by juztas** [comment]
Solved here:https://github.com/sdn-sense/siterm/pull/72
