### ISSUE TITLE
Modeling of scheduled services

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#73]
@juztas Currently DTN-RM does not update model immediate after a service / connection is scheduled to start in a future time. The model will only show up when the provisioning is kicked off. This will cause overbooking of the same resource / schedule.

A minimal feature requires the following patch. 
* [x] 1. Make the model change immediately after delta is committed even if the connection has a lifetime that starts in the future. Accommodate cases like `start < current < end` time and end `< current` time upon accepting the delta. Also accommodate multiple new non-conflicting schedule on a same resource (e.g., VLAN). 
* [x] 2. Remove the model change upon cancellation no matter the connection has been provisioned or not. 
* [x] 3. Optional: Remove the model change when the connection is deactivated after lifetime expires (end time < current time).

A phase-I enhancement to the minimal feature.
* [x] 4. Tag the lifetime resource with `mrs:tag` == monitor:status:**scheduled** | activating | **activate-failed** | **active** | error | deactivating | **deactivate-failed**  | deactivated  (Bold font represents mandatory states. Other states are optional).
* [x] 5. Without doing monitor:status tag, comply with the assumption that SENSE-O will use lifetime timestamps to infer scheduled (t <= start), active ((start < t < end)and deactivated (end <= t) status.
* [x] 6. Optional: Add monitor:status:scheduled | activating | activate-failed | active | error | deactivating | deactivate-failed  | deactivated status to any other resources for trouble shooting (error triangulating) purpose. SENSE-O can use them to provide additional information to users/admins.

**Comment by xi-yang** [comment]
More  feature requirements are described in https://github.com/esnet/SENSE-Testbed/issues/92#issue-820370980 and https://github.com/esnet/SENSE-Testbed/issues/92#issuecomment-789205102.

**Comment by xi-yang** [comment]
Ran a few tests on Caltech nodea. mrs:tag was correct upon service creation (`scheduled`) then transitioned into `activating`. 

However, it got stuck in `activating`. The expectation is that once the service is activated it should (soon) become `active`. And optionally it will turn into `deactivating` and `deactivated` after end time (or model removed). 

<img width="385" alt="Screen Shot 2021-03-03 at 10 46 37 AM" src="https://user-images.githubusercontent.com/6596456/109836797-89516300-7c12-11eb-906a-3e2f7fdd2829.png">

**Comment by xi-yang** [comment]
In another test, I sent down two connections with conflicting schedules. Both get accepted and committed. 

First of all, a clarification that it is possible for orchestrators to send down conflicting schedules. There are couple of legitimate scenarios. One is that you have multiple orchestrators. Another is that even a same orchestrator may serve simultaneous requests.

So the RM needs to make its own judgement and refuse conflicting schedule. 

<img width="420" alt="Screen Shot 2021-03-03 at 11 09 02 AM" src="https://user-images.githubusercontent.com/6596456/109837297-08469b80-7c13-11eb-893b-602e7fb2ba80.png">
<img width="424" alt="Screen Shot 2021-03-03 at 11 08 39 AM" src="https://user-images.githubusercontent.com/6596456/109837298-08df3200-7c13-11eb-8b17-aebc412adcd8.png">

**Comment by xi-yang** [comment]
I have seen cases that (non-conflicting) second schedule on the same resource (VLAN) got committed but not able to verify. 

Another odd around multiple schedules on the same VLAN is that cancel a first active service will take the `bandwidthService` away from a later one. 

<img width="391" alt="Screen Shot 2021-03-03 at 11 27 40 AM" src="https://user-images.githubusercontent.com/6596456/109838397-1ea12700-7c14-11eb-80a2-a65a8be55cdb.png">
<img width="392" alt="Screen Shot 2021-03-03 at 11 27 21 AM" src="https://user-images.githubusercontent.com/6596456/109838404-1fd25400-7c14-11eb-99c3-373cdc9e58ef.png">

**Comment by juztas** [comment]
For conflicting schedules - you said Orchestrator will take care of that - so RM is not checking that. Can be changed - but how we define conflicting is another issue. 
Remaining in activating - this is correct ;) Agent fails to set resource - so it remains in activating state. For now, activating-failed is disabled - until we have a plan how we want to deal with it and report back upper. Also this delta: 10ceb27f-0fe8-447e-9488-610b54c3e358 with `urn:ogf:network:test1.ultralight.org:2021:service+vsw:s0:conn+47493420-1e13-4176-980d-84e750d93938:resource+links-Connection_1:vlan+1797` is weird - it did not had any changes present - what should be done with such?
No, there will be no `deactivating and deactivated` - as once it reches remove state - it will be removed.

**Comment by xi-yang** [comment]
> For conflicting schedules - you said Orchestrator will take care of that - so RM is not checking that. Can be changed - but how we define conflicting is another issue.

I took that back. I did not think it through. There are corner cases as stated above. Any overlapping of schedules on a same VLAN interface is a conflict. 

> Remaining in activating - this is correct ;) Agent fails to set resource - so it remains in activating state. For now, activating-failed is disabled - until we have a plan how we want to deal with it and report back upper. Also this delta: 10ceb27f-0fe8-447e-9488-610b54c3e358 with `urn:ogf:network:test1.ultralight.org:2021:service+vsw:s0:conn+47493420-1e13-4176-980d-84e750d93938:resource+links-Connection_1:vlan+1797` is weird - it did not had any changes present - what should be done with such?
> No, there will be no `deactivating and deactivated` - as once it reches remove state - it will be removed.

Sounds right. As long as the status turns into either `active` or `activate-failed`, the orchestrator will be happy. And yes `deactivating and deactivated` are not needed here.

**Comment by juztas** [comment]
Done: https://github.com/sdn-sense/siterm/pull/75
