### ISSUE TITLE
Modeling of site L3 VPN for Rucio/SENSE integration

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#93]
This requires the following L2 and L3 modeling changes.

For advertisement: 
1. Model L2 switching fabric as a single abstract switch per DTN. Do not expose individual switches. Ideally we can have a single SwitchingService per site. But having one per DTN per site is also fine.
2. Add an L3 RoutingService per site to model end site L3VPN capability. This is in addition to the existing per-DTN RoutingService that models on-host routes.

For provisioning:
1. Add VLAN ports on host and abstract site switch but do not add VLAN SwitchingSubnet as this is not a continuous L2 circuit.
2. SwitchingSubnets in WAN remain the same.
3. Use L3 RoutingService `providesRoutingTable` to add a per service instance routing table. 
4. Use `RoutingService:providesRoute` and `RoutingTable:hasRoute` to add routes based on dynamic L2 VLAN interface and destination IP prefixes as specified in the service request. This connects the DTN VLAN to WAN VLAN at the site edge at L3.
5. Add L3 IP addresses and routing model on DTN host as before. 
6. L3 routing are unidirectional. Routes need to be modeled for both directions.

![SiteRM-L3VPN-modeling](https://user-images.githubusercontent.com/6596456/148790201-d4c616e8-1ab1-43b8-a806-25a2e0d3c12f.png)

**Comment by xi-yang** [comment]
Assignee: @juztas 
Watchers: @tomlehman

**Comment by xi-yang** [comment]
In the case, we must expose all the site switches. One alternative type of modeling (type-2) will look like the below. 
* This gets rid of the per-site switching and adds interconnected switch nodes.
* The routingService remains per-site so that RM can flexibly determine how to apply a per-site routing policy.
* The delta model will be no different than the above (type-1), meaning the extra internal switching details will not be included in the deltas that are for site L3 routing services. They may be used for providing details for L2 services.
![SiteRM-L3VPN-modeling-type-2](https://user-images.githubusercontent.com/6596456/149677996-ca75846b-c08a-41cf-be3b-390f8274d531.png)

**Comment by xi-yang** [comment]
We could also support another alternative type of modeling (type-3) that ties routingService to a specific site switch as shown in the below.
* We will then add detailed L2 and L3 hops in the delta modeling. 
![SiteRM-L3VPN-modeling-type-3](https://user-images.githubusercontent.com/6596456/149678078-2c3c68fc-6061-4a54-a4bb-78e984c9c01a.png)

**Comment by xi-yang** [comment]
The below diagram depicts the model of a service instance in red color.
* The L3 portion is configured on the site router only. It then transport over a L2 service between sites. 
* The L2 portion can be P2P or MP that consist of WAN and site path segments.
* Future L2 portion may be replaced with MPLS (EVPN) L2 or L3 services across the WAN.
* This example is based on the Type-3 site modeling above that assumed a RoutingService on a specific site router / switch. Type-1 and Type-2 modeling will have very similar per-instance models, just with different L2 attaching points.
* The local portion (from routingService towards host) is assumed to be statically configured for now. We can potentially added dynamical L2 or L3 portion there as needed.

![SiteRM-L3VPN-modeling-Page-3](https://user-images.githubusercontent.com/6596456/152598694-e0974cf7-8edd-4114-b848-5865d72c6c47.png)

**Comment by xi-yang** [comment]
@juztas There are two types of ipv6 pools in the model. One is for gateway private addresses, let's associate it with the L2 port that designated as the gateway towards external. For example, G1 in the above diagram. 
```
mrs:type "ipv6-address-pool";
mrs:value "pool of ipv6 private addresses for gateway".
```

The other is for the IPv6 subnets used by, say, the DMM.  That should be associated with the routingService, where you have `ipv6-floatingip-pool`. Let's replace it with:
```
mrs:type "ipv6-subnet-pool";
mrs:value "pool of public ipv6 subnets for the site".
```

**Comment by xi-yang** [comment]
With the `ultralight.org:2013 -- ultraligh1.org:2013` setting, the following deltas are generated from sense-o.es.net using the profile named `IPv6-Site-L3-Dev2 ` (ID: ce96ba09-146c-4e43-9506-4012b47fc6cf).

To ultralight.org RM:
[ultralight.ttl.txt](https://github.com/sdn-sense/siterm/files/8427624/ultralight.ttl.txt)
 
To ultralight1.org RM:
[ultralight1.ttl.txt](https://github.com/sdn-sense/siterm/files/8427626/ultralight1.ttl.txt)


Note that due to some flaw in L2 path modeling, the source end (ultralight.org) has SwitchingSubnet with a single VLAN port included while the destination end (ultralight1.org) does not have SwitchingSubnet with only VLAN port under physical port. Like below

```
<urn:ogf:network:ultralight.org:2013:dellos9_s0:service+vsw>
        <http://schemas.ogf.org/mrs/2013/12/topology#providesSubnet>
                <urn:ogf:network:ultralight.org:2013:dellos9_s0:service+vsw:conn+995022a3-575b-4159-88b0-ebf96c59cef9:vt+l2-policy-Connection_1:vlan+1795> ;

urn:ogf:network:ultralight.org:2013:dellos9_s0:service+vsw:conn+995022a3-575b-4159-88b0-ebf96c59cef9:vt+l2-policy-Connection_1:vlan+1795>
        a       <http://schemas.ogf.org/mrs/2013/12/topology#SwitchingSubnet> ;
        <http://schemas.ogf.org/mrs/2013/12/topology#tag>
                "urn:ogf:network:service+995022a3-575b-4159-88b0-ebf96c59cef9:vt+l2-policy::Connection_1" ;
        <http://schemas.ogf.org/nml/2013/03/base#belongsTo>
                <urn:ogf:network:ultralight.org:2013:dellos9_s0:service+vsw> ;
        <http://schemas.ogf.org/nml/2013/03/base#encoding>
                <http://schemas.ogf.org/nml/2012/10/ethernet#vlan> ;
        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>
                <urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-1:vlanport+1795> ;
        <http://schemas.ogf.org/nml/2013/03/base#labelSwapping>
                "false" .



<urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-1>
        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>
                <urn:ogf:network:ultralight.org:2013:dellos9_s0:hundredGigE_1-1:vlanport+1795> .


============================== vs ==========================================


<urn:ogf:network:ultralight1.org:2013:dellos9_s0:hundredGigE_1-6>
        <http://schemas.ogf.org/nml/2013/03/base#hasBidirectionalPort>
                <urn:ogf:network:ultralight1.org:2013:dellos9_s0:hundredGigE_1-6:vlanport+1795> .

```

It will be great if the Site RM can handle both cases. Otherwise, pick one case it prefers and I will change the other. @juztas

**Comment by xi-yang** [comment]
@juztas Here is updated delta model for `ultralight.org`.

Both `<topology> nml:hasService ...` and `mrs:tag` were artificially inserted by auxiliary computation model and are now gone. 
[ultralight2.ttl.txt](https://github.com/sdn-sense/siterm/files/8439051/ultralight2.ttl.txt)

**Comment by juztas** [comment]
pretty much all of this is present in this pull request:https://github.com/sdn-sense/siterm/pull/96
Already deployed at 2 Caltech sites. Soon at UCSD

**Comment by juztas** [comment]
Routing Information passed to Ansible hosts with this pull request: https://github.com/sdn-sense/siterm/pull/100
Dell templates to configure BGP and SONiC new parser also here: https://github.com/sdn-sense/siterm-startup/commit/5db884f9ff36be3cf09b26e8a4c46f3e2a14e13f

**Comment by juztas** [comment]
Seems we have pretty much all pieces in place. If anything is missing, feel free to re-open.
