### ISSUE TITLE
Problem with simultaneous cancelation requests

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#94]
**Describe the bug**
With multiples services / connections / deltas are created and activated, sending parallel cancellation requests will cause failures. 

Only the first will be served, others will encounter errors and lose socket connection for the request.

**To Reproduce**
1. Create multiple connections into active status from SENSE-O
2. Cancel all of them at the same time (using a CLI script) 
3. Observe logging of each services
<img width="1162" alt="Screen Shot 2022-03-22 at 9 37 34 AM" src="https://user-images.githubusercontent.com/6596456/159495268-fbfea571-024e-47d8-97c4-c3f06b107f67.png">

**Comment by xi-yang** [comment]
Note that this only exhibits at Cancel propagate stage. Parallel  Create and Reinstate worked fine.

**Comment by juztas** [comment]
Can you get me full log of whenever this was happenning? Mainly /var/log/httpd/error_log

**Comment by juztas** [comment]
The socket connection was solved with a Mariadb fix.
