### ISSUE TITLE
Misc Site-RM stability issues

### ISSUE THREAD

**Issue by xi-yang** [sdn-sense/siterm#95]
We are going to use this to track and resolve all the issues to make the deployment more stable. This is particularly for the observations that RMs demonstrate unstable behaviors after days of simple model pull operations. For example, some agent processes may crash after running for a while. 

@juztas Please examine these in the current deployments when they are present and then verify the fix in the refreshed Site-RM code. 

* [x] 1. Model pull shows 500 error from RM. See https://github.com/sdn-sense/siterm/issues/95#issuecomment-1088755803
* [x] 2. Lost connection to RM. RM httpd log shows `File exists: '/tmp/siterm-git-fetch-lockfile'`. See https://github.com/sdn-sense/siterm/issues/95#issuecomment-1130004416

**Comment by xi-yang** [comment]
1. On the starlight deployment, RM FE is on bare-metal host `sense-rm.starlight.net` and Agent on k8s host dtn110. 
<img width="1226" alt="Screen Shot 2022-04-05 at 10 03 59 AM" src="https://user-images.githubusercontent.com/6596456/161773374-173b4c29-e210-4749-93fc-408f3f7f4712.png">

**Comment by xi-yang** [comment]
> 1. On the starlight deployment, RM FE is on bare-metal host `sense-rm.northwestern.edu` and Agent on k8s host dtn110.
> 
> <img alt="Screen Shot 2022-04-05 at 10 03 59 AM" width="1226" src="https://user-images.githubusercontent.com/6596456/161773374-173b4c29-e210-4749-93fc-408f3f7f4712.png">

Was due to disk full.

**Comment by juztas** [comment]
Git fetch lock was separated from the Main processes. Already deployed at SDSC/Caltech/UMD
